### PR TITLE
Add pipecd

### PR DESCRIPTION
**Pull request by nghialv**
Hello,

This PR is for adding https://pipecd.dev/ to the tool list.

Thank you.

### CODE REVIEW

**Review by dimitropoulos — APPROVED** [review]
if
> Automatically watch and detect the new container images to deploy
from the website means that there's a reconciliation loop happening (as there appears to be) then sounds good!

**Comment by nghialv** [comment]
@dimitropoulos Thanks for your approval.

> Automatically watch and detect the new container images to deploy

This is the same as the docker registry monitoring feature of FluxCD.


Btw, PipeCD is watching the change of Git repositories to apply those changes.

**Comment by nghialv** [comment]
@dimitropoulos Hello, could you merge this PR?

**Comment by dimitropoulos** [comment]
image

It seems I no longer have permissions to do so (I no longer work at Weaveworks).  Maybe @stefanprodan can help?

**Comment by nghialv** [comment]
@stefanprodan Hello, could you please merge this PR?
Thank you.

**Comment by stealthybox** [comment]
Thanks for your contribution to the community

**Comment by nghialv** [comment]
Thank you for merging.

**Pull request merged**
