### PR TITLE
Add conceptual diagram of GitOps-based infrastructure

### PR DESCRIPTION
**Pull request by marccarre**
**Changelog**: add a diagram, for more "visual" people.

**Preview**: https://github.com/weaveworks/awesome-gitops/tree/diagram

**Note for posterity**: 
Should one want to modify the diagram in the future, sources are available [here](https://docs.google.com/drawings/d/1-0ED6x6o7pjT2ZBcRq7Onk_MFmJow3ejxcADQ-7s4KA).

### CODE REVIEW

**Comment by stefanprodan** [comment]
I find it confusing that we have TF in there, there no gitops operator that work with TF files and I think it sends the wrong message.

**Comment by dimitropoulos** [comment]
GitOps

I fiddled with it a bit.  lemme know what you think.

In a way, as far as I understand.. there _is_ a tool that uses gitops with cloudformation: eksctl.  still.. probably best to leave that bit out since it's not crucial to the overall point that the diagram is trying to show.

**Comment by stefanprodan** [comment]
@dimitropoulos this looks great, I would replace:
- `Target State` with `Desired State`
-  `Flux` with `GitOps operator`

**Comment by dimitropoulos** [comment]
sounds good on the target state thing.

re: GitOps operator.. the point of the dark blue boxes was to show the concrete name of the tool.  I don't deeply care, to be honest, one way or the other... but it seems more consistent to name the actual tool.  I was thinking of including some others (e.g. `Cloud Run`).  Maybe could we brainstorm on that route for a minute of what else we might add alongside `Flux`?

**Comment by marccarre** [comment]
- +1 on removing Terraform -- I wanted to show that the GitOps philosophy applies to any way to do "declarative IaC", but I agree it may be more confusing than anything else.
- +1 for "_Desired State_" -- It is actually what I had initially, but I changed the diagram to match the text we had so far. I'll do the reverse and change the text instead to also be "_desired state_".
- +1 for "_GitOps operator_" -- This seems like the right terminology.
- -1 on being too specific and too "deep" into Kubernetes at this stage. This may be fine as a second diagram, with more details, technology names thrown out, etc. , but it may be a bit overwhelming for someone new to all these things. I'd rather not mix implementation details with the definition.

**Comment by marccarre** [comment]
I've "forked" the diagram to have two versions:
- [a "lighter" version](https://docs.google.com/drawings/d/1bmGK1Rji09GmgTIC7La88gQxWwMh5upALMwcUmNBDzw), which is more of a conceptual diagram for the definition section ;
- [a "heavier" version](https://docs.google.com/drawings/d/1-0ED6x6o7pjT2ZBcRq7Onk_MFmJow3ejxcADQ-7s4KA), with all the changes @dimitropoulos did, for another section (to be decided), where we can have more implementation details, name of tools, etc. to give an idea of an actual setup.

Also:
- +1 on removing Terraform -- I wanted to show that the GitOps philosophy applies to any way to do "declarative IaC", but I agree it may be more confusing than anything else.
- +1 for "_Desired State_" -- It is actually what I had initially, but I changed the diagram to match the text we had so far. I'll do the reverse and change the text instead to also be "_desired state_".
- +1 for "_GitOps operator_" -- This seems like the right terminology.
- -1 on being too specific and too "deep" into Kubernetes at this stage. This may be fine as a second diagram, with more details, technology names thrown out, etc. , but it may be a bit overwhelming for someone new to all these things. I'd rather not mix implementation details with the definition.
- -1 on unidirectional arrows -- To me it gives the impression that tools like Kubediff would modify the Git repository.

**Comment by marccarre** [comment]
Branch updated, PTAL: https://github.com/weaveworks/awesome-gitops/tree/diagram

**Comment by dimitropoulos** [comment]
(for the record feel free to change what you like of that original diagram.  there's revision history so we can always go back)

**Comment by kalbir** [comment]
I like the "light" diagram as it is on @marccarre's latest version but I think it is missing one thing that made @dimitropoulos's very strong: the idea of the gitops operator implementing a control loop. 

I think if the latest digram had to and from the cluster (as in @dimitropoulos's version) with the little blocks of text he added that would be great. 

I agree overall with removing the specifics of the implementation/software and instead keeping it at the level of "gitops operator" doing all the work.

**Comment by marccarre** [comment]
I agree having something illustrating the OODA loop would be good. 
I'll try to come up with another version then.

**Comment by marccarre** [comment]
So... I came up with:

1. [GitOps (conceptual diagram ; OODA loop)](https://docs.google.com/drawings/d/1JtV1cdBEI-INzaMZoSnHy7bj1eR6--PaeTCfTUQftq4/edit), and
2. [GitOps (conceptual diagram ; OODA loop ; w/o text)](https://docs.google.com/drawings/d/1I2fuzvY9JNWZZxTbfUFVN3FjL5Lcwiv_ak1IcNOpaeU/edit), the idea being that the equivalent text could be added below the diagram.

and after an offline discussion with @kalbir, I decided to update the PR to go for 1.

Hopefully, it will please everyone & we'll be able to reach consensus (or at least agree to disagree and merge this for now, as we can always change/improve later 🙂).

PTAL: https://github.com/weaveworks/awesome-gitops/tree/diagram

**Comment by dimitropoulos** [comment]
@bia is there any chance you or @miklosp can spend, oh, 10 minutes with this to make it look prettier since it's going to be "front and center"?

@marccarre looks good to me!

**Comment by bia** [comment]
Ok, [here's a try](https://docs.google.com/drawings/d/1JtV1cdBEI-INzaMZoSnHy7bj1eR6--PaeTCfTUQftq4/edit?usp=sharing).

I had a bit of confusion with the file copying, so instead I just named Marc's last version 'Marc latest' within the same doc. Unfortunately that broke one of his links. Sorry @marccarre :(

**Comment by dimitropoulos** [comment]
WOW! THIS IS A GREAT IMPROVEMENT!

GitOps (conceptual diagram ; OODA loop) (1)


I made a few very minor tweaks (aligning the documents, upping the opacity since after aligning the lines were overlapping a lot more with the text, and adding a border to the "gitops operator" section in the middle and the "observability tools" section so that the dotted line (which is a border) lines up with the edge of the header (dark blue filled in part)).

I'm totally happy with this being the current thing we roll with for now.  @marccarre since it's been useful to have the google docs drawing for iterating: could we possibly include it somewhere that's _not_ the main readme for use later as updates arise?

**Comment by marccarre** [comment]
Thanks a lot @bia & @dimitropoulos. I've exported the [diagram's latest version](https://docs.google.com/drawings/d/1JtV1cdBEI-INzaMZoSnHy7bj1eR6--PaeTCfTUQftq4/edit) as a SVG and updated the branch accordingly. PTAL: https://github.com/weaveworks/awesome-gitops/tree/diagram

Also, not sure I understand what you meant by:
> could we possibly include it somewhere that's not the main readme for use later as updates arise?

**Pull request merged**
